version: '3'

services:
  dbservice:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3307"
    networks:
      - examportal
  
  appservice:
    build: ./examserver
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/exam?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8085:9295"
    networks:
      - examportal

networks:
  examportal:
